export const MOSCOW_NP_FLIGHT = '/?params=MOWNP1'
export const MOSCOW_LONDON_WITH_DATES_21JUNE_17JULY = '/?params=MOW2106LON17071'
export const MULTIWAY_PARAMS_MOW_IST_5JULY_IST_LON_9OCTOBER = '/?params=MOW0507IST0910LON1'
export const WEEKENDS_SERVICE = '?params=MOW1&service=weekends'
export const ORIGIN_IS_MOSCOW = '/?params=MOW1'
export const SAINT_PETERSBURG_MOSCOW_FLIGHT = '/?params=LEDMOW1'
export const MOSCOW_BANGKOK_FLIGHT = '/?params=MOWBKK1'
